### ISSUE TITLE
Test is too strict, deprecation only concerns first character.

### ISSUE THREAD

**Issue by traylenator** [fiddyspence/puppetlint-variablecase#7]
This test trips on a variable name such as 

```puppet
define flume::agent (
  $jvm_Xms              = '50m',
}
```

however the only deprecation I can find is 

https://tickets.puppetlabs.com/browse/PUP-1808

which only concerns the first character.

https://docs.puppet.com/puppet/4.8/reference/lang_variables.html#naming

says variable names should match

```
\A\$[a-z0-9_][a-zA-Z0-9_]*\Z
```

so indeed *jvm_Xms* is legal.

**Comment by fiddyspence** [comment]
Hi.  I see what you're saying about the legality of mixed case vars in the parser and don't disagree - mixed case vars are legal.  

However, #1 also raised this point, and I haven't really changed my mind since.

Where I think you should be is that using unit/acceptance tests (rspec-puppet and/or something like beaker/test-kitchen) you'll catch the illegal variable uses and break compilation ($Foo goes bang) and leave the legal instances alone ($bAr does not go bang).

If you don't mind having mixed case vars in your code, then this plugin probably isn't for you, because this is a style test for those (like me) who really don't want mixed case $vARs in their code at all, and are happy to leave the legality of the actual variable names to the parser (which changes over time).

You'll see from #1 that the docs and the parser weren't in lockstep back in the day, and I don't really want to have to reimplement those rules here, when all I care about in this context is disallowing mixEd_cAse despite the fact that the puppet parser thinks its legal.

**Comment by fiddyspence** [comment]
Also, and I always forget this - you can always turn the test off on a per module basis e.g.

```PuppetLint.configuration.send('disable_variable_contains_upcase')```

**Comment by traylenator** [comment]
Thanks for the reply, I of course did not find #1 .

A new lint test probably makes sense then, will look into - thanks again.
